### ISSUE TITLE
Lên form các câu hỏi cho chuyên khoa

### ISSUE THREAD

**Issue by joehua87** [joehua87/giupnhaumuadich#6]
Collect các câu hỏi để bệnh nhân dễ điền, các field chung có thể note lại rồi dùng chung cho các bệnh
Ví dụ về tai mũi họng: lấy thông tin trên https://form.jotform.com/211953601438050

```yaml
  - name: name
    label: Họ tên
    type: text
  - name: age
    label: Tuổi
    type: number
  - name: facebook_uid
    label: Link Facebook
    type: text
  - name: Họ tên
    label: Số điện thoại / Zalo
    type: text
  - name: symptoms
    label: Triệu chứng
    type: multi_select
    options:
    - Đau tai
    - Chảy mủ tai
    - Ù tai
    - Nghe kém
    - Nghẹt mũi
    - Chảy mũi
    - Chảy mũi sau
    - Đau mũi
    - Hắt hơi (nhảy mũi)
    - Đau mặt - nặng mặt
    - Đau họng
    - Nuốt đau
    - Nuốt khó
    - Khàn tiếng
    - Khối vùng cổ
    - Khối vùng đầu mặt
  - name: note
    label: Mô tả thêm về bệnh
    type: textarea
  - name: other_desease
    label: Bệnh nền
    type: multi_select
    options:
    - Tiểu đường
    - Tăng huyết áp
    - Viêm gan mạn tính
    - Thiếu máu cơ tim
    - Ung thư
```

**Comment by joehua87** [comment]
thêm các field sau:

```
- name: height
  label: Chiều cao (cm)
  type: text
- name: weight
  label: Cân nặng (kg)
  type: text
```

- attach hình & toa thuốc đang dùng/cũ 
- kết quả xét nghiệm và cận lâm sàng đã có

**Comment by joehua87** [comment]
Câu hỏi dành riêng cho nghi nhiễm Covid:

```yaml
- name: f0_f1
  label: F0 hay F1
  type: select
  options: 
  - F0
  - F1
- name: mo_ta_chi_tiet
  label: Tiếp xúc được mấy ngày, nhà có ai nữa là F0,1 nữa ko?
  type: textarea
- name: mo_ta_chi_tiet
  label: Triệu chứng
  type: select
  options:
    - sốt dưới 38.5 °C
    - sốt trên 38.5 °C
    - ho khan
    - mệt mỏi
    - đau nhức
    - đau họng
    - tiêu chảy
    - viêm kết mạc
    - đau đầu
    - mất vị giác hoặc khứu giác
    - da nổi mẩn hay ngón tay hoặc ngón chân bị tấy đỏ hoặc tím tái
    - khó thở
    - đau hoặc tức ngực
    - mất khả năng nói hoặc cử động
  ```

**Comment by hangtruong** [comment]
thêm các field sau:

```yaml
- name: height
  label: Chiều cao (cm)
  type: text
- name: weight
  label: Cân nặng (kg)
  type: text
- name: sex
  label: Giới tính
  type: select
  options:
  - Nam
  - Nữ
- name: female_only
  label: Dành cho nữ
  type: multi_select
  options: 
  - Đang có thai
  - Đang cho con bú
- name: note
  label: Đang có thai mấy tháng
  type: text
- name: note
  label: Đang cho con bú mấy tháng
  type: text
- name: di_ung_thuoc
  label: Tiền sử dị ứng thuốc
  type: select
  options: 
  - Không
  - Có 
- name: di_ung_thuoc_chi_tiet
  label: Mô tả chi tiết tên thuốc/biệt dược dị ứng
  type: string
```

- attach hình & toa thuốc đang dùng/cũ 
- kết quả xét nghiệm và cận lâm sàng đã có

**Comment by hangtruong** [comment]
Câu hỏi dành riêng cho nghi nhiễm Covid:

```yaml
- name: f0_f1
  label: F0 hay F1
  type: select
  options: 
  - F0
  - F1
- name: mo_ta_chi_tiet
  label: Tiếp xúc được mấy ngày, nhà có ai nữa là F0,1 nữa ko?
  type: textarea
- name: mo_ta_chi_tiet
  label: Triệu chứng
  type: select
  options:
    - sốt dưới 38.5 °C
    - sốt trên 38.5 °C
    - ho khan
    - mệt mỏi
    - đau nhức
    - đau họng
    - tiêu chảy
    - viêm kết mạc
    - đau đầu
    - mất vị giác hoặc khứu giác
    - da nổi mẩn hay ngón tay hoặc ngón chân bị tấy đỏ hoặc tím tái
    - khó thở
    - đau hoặc tức ngực
    - mất khả năng nói hoặc cử động
  ```
